---
kind: secret
name: kubeconfig

get:
  path: buildx
  name: kubeconfig

---
kind: pipeline
name: default

services:
  - name: docker
    image: docker:19.03-dind
    entrypoint:
      - dockerd
    command:
      - --dns=8.8.8.8
      - --dns=8.8.4.4
      - --log-level=error
    privileged: true
    volumes:
      - name: docker-socket
        path: /var/run

steps:
  - name: setup-ci
    image: autonomy/build-container:latest
    commands:
      - git fetch --tags
      - apk add coreutils
      - echo -e "$BUILDX_KUBECONFIG" > /root/.kube/config
      - docker buildx create --driver kubernetes --driver-opt replicas=2 --driver-opt namespace=ci --driver-opt image=moby/buildkit:v0.6.2 --name ci --buildkitd-flags="--allow-insecure-entitlement security.insecure" --use
      - docker buildx inspect --bootstrap
    environment:
      BUILDX_KUBECONFIG:
        from_secret: kubeconfig
    privileged: true
    volumes:
      - name: docker-socket
        path: /var/run
      - name: docker
        path: /root/.docker/buildx
      - name: kube
        path: /root/.kube

  - name: unit-tests
    image: autonomy/build-container:latest
    pull: always
    commands:
      - make unit-tests
    when:
      event:
        include:
          - pull_request
    volumes:
      - name: docker-socket
        path: /var/run
      - name: docker
        path: /root/.docker/buildx
      - name: kube
        path: /root/.kube
    depends_on:
      - setup-ci

  - name: unit-tests-race
    image: autonomy/build-container:latest
    pull: always
    commands:
      - make unit-tests-race
    when:
      event:
        include:
          - pull_request
    volumes:
      - name: docker-socket
        path: /var/run
      - name: docker
        path: /root/.docker/buildx
      - name: kube
        path: /root/.kube
    depends_on:
      - setup-ci

volumes:
  - name: docker-socket
    temp: {}
  - name: docker
    temp: {}
  - name: kube
    temp: {}
---
kind: pipeline
name: notify

clone:
  disable: true

steps:
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: proj-talos-maintainers
    when:
      status:
        - success
        - failure

trigger:
  status:
    - success
    - failure

depends_on:
  - default
